### ISSUE TITLE
Muffin Builder no longer working

### ISSUE THREAD

**Issue by davidkahn** [impress-org/give#3852] opened 2018-11-19 18:25 UTC
# Bug Report

## User Story

As an editor/admin of our site, I want to be be able to edit existing blocks so that I can update content.

## Current Behavior
There is an expected javascript action that is not firing.

## Expected Behavior
Muffin Builder's Edit buttons should popup in the same window but nothing is showing up. 

## Bug Type
This worked in a previous version. If GiveWP is disabled, Muffin Builder works.

## Steps to Reproduce

1. Click on Edit Page
2. Click on Muffin Builder Edit button
3. Page doesn't do anything.

## Possible Solution
Ravinder fixed this in a previous version.

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by ravinderk** [comment] 2018-11-20 03:51
@kevinwhoffman Previously we solved this issue, maybe reappear: https://github.com/impress-org/give/issues/3353

**Comment by kakshak** [comment] 2018-11-26 08:02
@kevinwhoffman I've checked the functionality of `Muffin Builder` with `Give 2.3.2` plugin and it's working fine as per expected. I think it is related to #3353 coz I am not able to reproduce this issue and I don't see any Javascript error in a console as well.

Please review the below attached video and let me know your thoughts on this.

## Video
https://www.useloom.com/share/97f63b3058ab4bb0a479d29a3ae31223

**Comment by DevinWalker** [comment] 2018-11-27 18:54
@davidkahn please let us know how to reproduce the issue as we've been unable to. Closing until we can reliably reproduce.

**Closed by DevinWalker** 2018-11-27 18:54 UTC
