### ISSUE TITLE
fix: ensure compatibility with elementor finder 

### ISSUE THREAD

**Issue by marutim** [impress-org/give#3912] opened 2018-12-26 17:39 UTC
# Bug Report

## User Story

As a user, I would like to use GiveWP and Elementor together.

At the moment when both are active, I can not use the Elementor's finder feature. It does not find the pages, but if I deactivate the GiveWP plugin, I can use the finder without any issue.

## Current Behavior

Elementor's finder does not work as intended with GiveWP activated.

## Expected Behavior

One should be able to use Elementor's finder feature with GiveWP activated.

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install and activate both GiveWP and Elementor.
2. Make sure you have at least one page which uses elementor's elements in the content.
3. While you are in admin, click CMD + e ( CNTRL + e ) to open the finder.
4. Try and search the page by name.
5. Now deactivate GiveWP and try steps 3-4, you will be able to search the page.

## Visuals

![1](https://user-images.githubusercontent.com/3498917/50452825-87205980-0962-11e9-8416-0e3694387ba0.png)
![2](https://user-images.githubusercontent.com/3498917/50452827-88ea1d00-0962-11e9-894c-fce1c2c0def3.png)

## Related

HS link: https://secure.helpscout.net/conversation/739070885/31636/

## Acceptance Criteria

- [ ] Elementor's Finder feature should work as intended with GiveWP activated.

## Environment

<details>
    ### WordPress Environment ###

Home URL: http://give-elementor.local
Site URL: http://give-elementor.local
WP Version: 5.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give-elementor.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.1
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: 2.3.1
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give-elementor.local/donation-confirmation/
Failure Page: http://give-elementor.local/donation-failed/
Donation History Page: http://give-elementor.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Other Active Plugins ###

Elementor: by Elementor.com – 2.3.8

### Theme ###

Name: Twenty Nineteen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by nishitlangaliya** [comment] 2019-01-08 04:13
@kevinwhoffman , Currently moving to bloc. I need help to find cause of issue.

**Comment by kevinwhoffman** [comment] 2019-01-09 21:38
Punting this to 2.4.1 until we move time to look into it.

**Comment by Benunc** [comment] 2019-03-06 17:41
From a customer: https://screencast-o-matic.com/watch/cqef3Q0rLP

I replicated on a fresh install. 

1. Install Elementor from the repo before installing Give
1. Create a new page named "Kids are Fun and Inexpensive" (just change the title and publish, doesn't even have to be in the Elementor editor)
1. Navigate to a different admin screen (`plugins.php` will do, since you'll need it in a next step)
1. Press `CMD-E` to bring up the elementor finder
1. Type "Kids" into the finder.
1. You will see the new page you created in an edit section
1. Install Give from the repo and activate.
1. Repeat steps 4 and 5.
1. You will not see the Edit Section in the finder at all.

No console errors, but when Give is active, the EDIT section of the elementor finder does not appear.

**Comment by kevinwhoffman** [comment] 2019-03-12 18:23
@JasonTheAdams We've seen a few reports of incompatibility with Elementor's finder feature. See https://github.com/impress-org/give/issues/3912#issuecomment-470204101 for the most complete and up-to-date summary of the issue. The screencast does a great job of highlighting exactly what's wrong, thought we still don't know the cause or solution.

**Comment by JasonTheAdams** [comment] 2019-03-12 19:54
So this is an interesting issue, and it actually surfaces a higher-level issue.

When the user brings up finder and starts typing, an AJAX request is triggered which ends up using the [Edit::get_category_items](https://github.com/elementor/elementor/blob/master/core/common/modules/finder/categories/edit.php#L57) method. This method does a [multi-post-type search query](https://github.com/elementor/elementor/blob/master/core/common/modules/finder/categories/edit.php#L57). At this point GiveWP gets involved by hooking into the `posts_where`, `posts_join`, `posts_groupby`, and `posts_orderby` hooks, which all ultimately call the same method: [Give_DB_Meta::__rename_meta_table_name_in_query](https://github.com/impress-org/give/blob/release/2.4.2/includes/class-give-db-meta.php#L269). If the form post type is included in the query posts types the [Give_DB_Meta::__rename_meta_table_name](https://github.com/impress-org/give/blob/release/2.4.2/includes/class-give-db-meta.php#L287) method is called. This method renames the `wp_posts` and `wp_postmeta` tables to use the new form tables.

So here's the rub. In going the route where `WP_Query` is hooked into in order to swap out table names for the form post type meta, the trade-off was made that this applies to cases where the form is the singular post type being queried, as well as cases where it's simply one of many post types. In this case, the wrong meta tables are being queried for the `post` and `page` post types, therefore no pages or posts are returned as the meta queries are false.

The challenge here is that the posts come from a unified table — `wp_posts` — whereas the meta may be different tables. `WP_Query` aside, the SQL would have to look something like:
```sql
SELECT * FROM wp_posts
  JOIN wp_postmeta ON wp_posts.ID = wp_postmeta.post_id
  JOIN wp_give_formmeta ON wp_posts.ID = wp_give_formmeta.form_id

WHERE
  (
    wp_posts.post_type = 'give_forms'
    AND wp_give_formmeta.meta_key = 'foo'
  )
  OR
  (
    wp_posts.post_type IN ('page', 'post'
    AND wp_postmeta.meta_key = 'bar'
  )
```

This, unfortunately, is by no means a simple task. What's especially hard is knowing exactly which meta belongs to which meta table.

---

The only "quick fix" option I can see here would be to not swap out the meta table names in the case that the `give_forms` post type is in an array of queried posts, and not the only one. The `WP_Query` instance could also be checked to see if it's a search query. This, at least, would fix the Elementor issue.

Hope this helps! Let me know if anyone has any thoughts or questions! I feel making the call on this one is not quite in my 2-day old jurisdiction. 😉

**Comment by kevinwhoffman** [comment] 2019-03-12 20:52
@JasonTheAdams Good sleuthing. 🕵️It sounds like we're dealing with this issue on two levels:

1. Surface-level - Prevent Elementor Finder from breaking.
2. Underlying - Prevent Give from breaking meta queries when it is not the only post type involved.

Let's see what we can do to solve the underlying issue, which will in turn solve the issue with Elementor.

## Possible Solution

> The only "quick fix" option I can see here would be to not swap out the meta table names in the case that the give_forms post type is in an array of queried posts, and not the only one.

This seems like the most reasonable fix that would solve not only the Elementor issue but also the larger issue that Jason described where Give would break meta queries when it is part of a query with other post types.

We can discuss on the dev team call and decide.

**Comment by kevinwhoffman** [comment] 2019-03-13 04:36
@JasonTheAdams We discussed on dev team call and all agree to move forward with the proposed solution above. I am assigning to @ravinderk to make the modifications to the filters so that we are not filtering queries that involve other post types besides `give_forms`.

Ravinder please tag Jason for review of this PR.

**Closed** 2019-03-13 06:33 UTC

**Comment by ravinderk** [comment] 2019-03-13 06:50
ref: test passed -> https://travis-ci.org/impress-org/give/builds/505606354

**Comment by JasonTheAdams** [comment] 2019-03-13 15:22
@ravinderk Thanks for hopping on that! I'm a bit confused, though; it looks like you committed to the `release/2.5.0` branch, but wasn't @kevinwhoffman saying to start another branch and make a PR for me to review? Should I just test the `release/2.5.0` branch, now?

**Comment by ravinderk** [comment] 2019-03-13 15:25
@JasonTheAdams  it was a minor change, that why I did not create pr. Can you test `release/2.5.0` for now?

**Comment by JasonTheAdams** [comment] 2019-03-13 16:02
@ravinderk Ok! Well, I tested against `release/2.5.0` and the finder is working properly. 👍
