### ISSUE TITLE
fix: ensure compatibility with Elementor page builder and Give

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3858] opened 2018-11-20 15:57 UTC
# Bug Report

## User Story

As a site admin, I want to add elements to a page within Elementor so that I can build and maintain the pages in my site with this page builder.

## Current Behavior

Whenever I have Give and Elementor activated on my site, I'm unable to drag and drop elements onto the page. The area where I'm attempting to drop the element takes a while to highlight, this shows it recognizes where it will be placed. When the area does highlight the element isn't added when I drop it.

There are no errors in the console, and no errors displaed on the page.

## Expected Behavior

I expect both plugins to work side by side, and elements to be added to pages when I'm using the Elementor editor.

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install the site at the password protected link attached
2. Attempt to add an element on the page called "Test About"
3. See that the area where the element will go takes a while to highlight
4. Nothing is added to the page when you drop the element

Protected link to the site backup:
https://drive.google.com/file/d/1u2bvXtd6rxtLC3M4_VIJUe_qXWyTKXyh/view?usp=sharing

## Visuals

![screen shot 2018-11-20 at 10 51 26 am](https://user-images.githubusercontent.com/20672471/48785187-46258d00-ecb2-11e8-8a91-5626fdb1ae5a.png)

Screencast of me walking through the issue:
https://screencast-o-matic.com/watch/cFXYoErliC

## Related

https://secure.helpscout.net/conversation/710009866/29352

## Acceptance Criteria

- [ ] When both plugins are activated, elements can be added to the page

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://firedeptsite.local
Site URL: http://firedeptsite.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home (#54)
Page for Posts: News (#344)
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: firedeptsite.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: 2.3.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://firedeptsite.local/donation-confirmation/
Failure Page: http://firedeptsite.local/donation-failed/
Donation History Page: http://firedeptsite.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Other Active Plugins ###

Elementor: by Elementor.com – 2.3.2

### Inactive Plugins ###

Advanced Custom Fields: by Elliot Condon – 5.7.7
All-in-One WP Migration: by ServMask – 6.76
AnyWhere Elementor Pro: by WebTechStreet – 2.10.3
Autoptimize: by Frank Goossens (futtta) – 2.4.1
Charitable: by WP Charitable – 1.6.6
Classic Editor: by WordPress Contributors – 0.5
Code Snippets: by Shea Bunge – 2.12.1
Custom Facebook Feed Pro Developer: by Smash Balloon – 3.6
Custom Post Type UI: by WebDevStudios – 1.6.0
Date and Time Widget: by Donna Peplinskie – 1.1.0
Duplicate Post: by Enrico Battocchi – 3.2.2
Elementor Pro: by Elementor.com – 2.2.0
Google Language Translator: by Rob Myrick – 5.0.48
GP Premium: by Tom Usborne – 1.7.3
Insert Pages: by Paul Ryan – 3.4.3
iThemes Security: by iThemes – 7.2.0
Login Logo: by Mark Jaquith – 0.9.0
MainWP Child: by MainWP – 3.5.1
Post Expirator: by Aaron Axelsen – 2.3.1.1
Profile Builder: by Cozmoslabs – 2.9.2
Shortcode For Current Date: by Imtiaz Rayhan – 2.0.0
Simple Custom Post Order: by Colorlib – 2.3.5
SSL Insecure Content Fixer: by WebAware – 2.7.0
WP AutoTerms: by WP AutoTerms – 2.2.1
Yoast SEO: by Team Yoast – 9.1

### Active MU Plugins ###

1&1 Product Subdomain: by 1&1 – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by kevinwhoffman** [comment] 2018-11-21 04:35
@kakshak Please review the screencast. Based on the customer report, this conflict only happens on certain pages in this site, so you will have to clone it locally to investigate. Let me know if you need access to the site backup.

**Comment by kakshak** [comment] 2018-11-22 11:20
@kevinwhoffman I've set up the website locally from the clone that Sam provided the link and I'll be playing around this functionality but only once for one page, I am able to reproduce this issue. Apart from that, I am not able to reproduce this issue for any of the pages.

@samsmith89 Please let me know when you're available. I need to discuss more regarding this functionality.

**Comment by samsmith89** [comment] 2018-11-27 13:10
@kevinwhoffman after looking around, I'm only getting reports from this customer. 

@kakshak Let me know when a good time would be, and I'll make it happen.

**Comment by samsmith89** [comment] 2018-11-27 13:36
Call Summary: 
Sam and Kakshak discussed this issue in Slack. Kakshak can only reproduce this issue on one page, and he is going to continue debugging this.

**Comment by kevinwhoffman** [comment] 2018-11-27 17:49
@kakshak @samsmith89 When Kakshak and I discussed this, he mentioned that it was an issue with one page on one site which he was not able to reliably reproduce. I suggest that we try to recreate that Elementor layout in a new page, and if we cannot reproduce the bug, then recommend that the user recreate the page and close the issue.

**Comment by kakshak** [comment] 2018-11-28 10:18
@kevinwhoffman @samsmith89 I've confirmed that there is no any confliction between `Give` and `Elementor page builder` plugin. I've checked with all other pages and all the elements are working fine. So, if a user wants to add any section then he can recreate the page and add the elements to it.

Below I attached the video of my findings. @kevinwhoffman please let me know your thoughts on this. Right now, I am closing this issue.

## Video
https://www.useloom.com/share/33325d9014a04cab89803becd0832f64

**Closed by kakshak** 2018-11-28 10:18 UTC
Labels: high-priority
