### ISSUE TITLE
fix(plugin-conflict): notices generate when Give is used with Groups plugins

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3538] opened 2018-07-31 09:55 UTC
## User Story
As an `admin`, I want the plugin to work flawlessly with any plugin.

ref: https://wordpress.org/support/topic/database-error-re-post_id-in-wp_give_formmeta/#post-10542529

Plugin: https://wordpress.org/plugins/groups/

## TODO
- [ ] Find cause
- [ ] Fix conflict

**Comment by Sidsector9** [comment] 2018-08-13 01:49
@ravinderk Can you please have a look into this? I am not able to reproduce the error.

**Comment by proaktion** [comment] 2018-08-15 16:18
Hi guys, in case this might be helpful for you I've made a suggestion here https://wordpress.org/support/topic/continuous-database-errors/#post-10593449

**Comment by ravinderk** [comment] 2018-08-17 04:17
@proaktion You right that we must stick to using WordPress table and we were doing same till `2.0`. We also know that postmeta queries are slow because most of the plugin use that only. That was a reason to have a custom postmeta table to increase performance and keep data organized.
Most e-commerce plugins like EDD, Woocommerce, and others are using custom meta tables only.

In addition, we are following the WordPress column name standard for naming the meta table column. Second column name in the meta table must be `{meta_type}_id` in our case meta type is different then post. So, it is now difficult for us to go back to old database architecture.

**Comment by mikejhale** [comment] 2019-08-01 21:33
Closing as there have been no recent conflicts.

**Closed by mikejhale** 2019-08-01 21:33 UTC
