### ISSUE TITLE
fix: prevent multiple plugin notices in multisite installs

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#3352] opened 2018-06-12 12:37 UTC
## User Story
As a `Admin`, I want to only see the update you plugin message once 

![image](https://user-images.githubusercontent.com/22215595/41290636-1db07922-6e6b-11e8-86ba-6ac17d61a8c4.png)

## Current Behavior

I currently see two notices of a new version of the plugin is available for download 

## Expected Behavior
I expect to see only one message as there are working in Normal sites 

## Visuals
![image](https://user-images.githubusercontent.com/22215595/41290721-5bb42638-6e6b-11e8-83be-23788af34c80.png)

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://givewpmultisubdirectory.local/subdirectory1
Site URL: http://givewpmultisubdirectory.local/subdirectory1
WP Version: 4.9.6
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_2_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewpmultisubdirectory.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givewpmultisubdirectory.local/subdirectory1/donation-confirmation/
Failure Page: http://givewpmultisubdirectory.local/subdirectory1/donation-failed/
Donation History Page: http://givewpmultisubdirectory.local/subdirectory1/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.1

### Other Active Plugins ###

Caldera Custom Fields: by Caldera Labs – 2.2.1
Caldera Forms: by Caldera Labs – 1.7.1.4

### Inactive Plugins ###

BuddyPress: by The BuddyPress Community – 3.0.0
Charitable: by WP Charitable – 1.6.1
Debug Bar: by wordpressdotorg – 0.9
Debug Bar Console: by koopersmith – 0.3
Debug Bar Cron: by Zack Tollman, Helen Hou-Sandi – 0.1.2
Debug Bar Extender: by Thorsten Ott, Automattic – 0.5
Developer: by Automattic – 1.2.6
Duplicate Post: by Enrico Battocchi – 3.2.2
Email Cop: by Ashfame – 0.1.1
Give - 2Checkout Gateway: by WordImpress – 1.1
Give - Authorize.net Gateway: by WordImpress – 1.3.3
Give - AWeber: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.2
Give - CCAvenue Gateway: by WordImpress – 1.0.1
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.1
Give - Development Plugin: by Raftaar1191 – 1.0.0
Give - Display Donors: by WordImpress, LLC – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.1.1
Give - Fee Recovery: by WordImpress – 1.6
Give - Form Countdown: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.3
Give - Gift Aid: by WordImpress – 1.1.1
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.4
Give - MailChimp: by WordImpress – 1.4
Give - Manual Donations: by WordImpress – 1.3.1
Give - Paymill Gateway: by WordImpress – 1.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Give - PDF Receipts: by WordImpress – 2.2.5
Give - Razorpay: by WordImpress – 1.1.4
Give - Recurring Donations: by WordImpress – 1.6.2
Give - Stripe Gateway: by WordImpress – 2.0.5
Give - Tributes: by WordImpress – 1.4.2
Give - Zapier: by WordImpress – 1.1.2
Gravity Forms: by rocketgenius – 2.2.6
Gravity Forms Signature Add-On: by Rocketgenius – 3.4
Loco Translate: by Tim Whitlock – 2.1.4
Log Deprecated Notices: by Andrew Nacin – 0.4
Log Viewer: by Markus Fischbacher – 14.05.04
Monster Widget: by Automattic – 0.3
Polylang: by Frédéric Demarle – 2.3.6
qTranslate-X: by qTranslate Team – 3.4.6.8
Query Monitor: by John Blackbourn & contributors – 3.0.1
Rewrite Rules Inspector: by Daniel Bachhuber, Automattic – 1.2.1
User Switching: by John Blackbourn & contributors – 1.3.1
WooCommerce: by Automattic – 3.4.1
WordPress Beta Tester: by Peter Westwood – 1.2.2
WP Hide & Security Enhancer: by Nsp Code – 1.4.9.1
WPML Multilingual CMS: by OnTheGoSystems – 3.9.4
WPS Hide Login: by WPServeur, NicolasKulka, tabrisrp – 1.3.4.2

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment] 2019-02-26 07:52
@kevinwhoffman I was not able to reproduce this issue.

![image](https://user-images.githubusercontent.com/1784821/53395675-6d35de00-39c8-11e9-82ee-279402f4a959.png)

But as you can see plugin version update notice has a gray border on top which separate plugin notice from plugin row. This message generates from `EDD_SL_Plugin_Updater ` class, Let me know if you want me to fix that.
(`p` tag missing from `div`: https://github.com/DevinWalker/EDD-Software-Licensing/blob/007b8d340eaaba6fae6cc0f0a09fc60a0d299d96/samples/edd-sample-plugin/EDD_SL_Plugin_Updater.php#L222)

we are hiding row border with custom styling in Give core:
![image](https://user-images.githubusercontent.com/1784821/53395903-17ae0100-39c9-11e9-8e6b-1c95d9f82467.png)


I check that `EDD_SL_Plugin_Updater` `1.6.18` does not fix this issue.
ref: https://github.com/DevinWalker/EDD-Software-Licensing/blob/master/samples/edd-sample-plugin/EDD_SL_Plugin_Updater.php

Note: This issue only appeared on multisite subsite because WordPress handles update tag on single sites.

**Comment by DevinWalker** [comment] 2019-02-27 20:55
I'm not seeing multiple notices either. Closing as it looks fine.

**Closed by DevinWalker** 2019-02-27 20:55 UTC
