### ISSUE TITLE
fix: prevent error when importing JSON settings file

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3907] opened 2018-12-18 15:11 UTC
# Bug Report

## User Story

As a site admin, I want to import the JSON settings file from another installation so that I can quickly get Give set up in another site.

## Current Behavior

When importing the JSON file from another site, I receive an error stating that the file is invalid.

## Expected Behavior

I expect to import the file without receiving an error message.

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Export a JSON file from another Give installation
2. In an empty site attempt to import the JSON settings file
3. See that an error is thrown stating the file is invalid, and the import doesn't take place

## Possible Solution

![screen shot 2018-12-18 at 10 00 39 am](https://user-images.githubusercontent.com/20672471/50162675-eae4bb80-02ac-11e9-93c6-c316847d05f7.png)

## Related

https://secure.helpscout.net/conversation/734568449/31321

## Acceptance Criteria

- [x] I can import a settings JSON file without receiving an error 
- [x] The import goes through without issue

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://destroy.local
Site URL: http://destroy.local
WP Version: 4.9.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home – Movement For A Peoples Party (#9)
Page for Posts: Blog (#84)
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: destroy.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.1
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: 2.3.0
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://destroy.local/donation-confirmation/
Failure Page: http://destroy.local/donation-failed/
Donation History Page: http://destroy.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #8597 ( N/A ) on 11/21/2018 at 11:25. Status VERIFIED
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1

### Theme ###

Name: bb-theme-child
Version: 
Author URL: 
Child Theme: Yes
Parent Theme Name: bb-theme-child
Parent Theme Version: 
Parent Theme Author URL: 
</details>

**Comment by kevinwhoffman** [comment] 2018-12-20 23:12
We tested a JSON settings import in WP 4.9.8 and it works. We confirmed the error is caused by the MIME type bug introduced in WP core 4.9.9/5.0.1. The core team is working on this issue and is planned for core 5.0.3. There is a gist available in this ticket but we need to confirm if it solves this JSON issue and possibly the related CSV issue:

https://core.trac.wordpress.org/ticket/45615#comment:13

**Comment by samsmith89** [comment] 2018-12-21 20:03
Sounds good. I'm updating the customer

**Comment by kevinwhoffman** [comment] 2019-01-03 04:46
Closing as WordPress core issue to be fixed in 5.0.3 with existing workaround.

**Comment by DevinWalker** [comment] 2019-01-18 22:48
Reopening as WP appears to not have resolve the issue for the JSON file type

**Comment by kevinwhoffman** [comment] 2019-01-18 23:13
Here's a [relevant Trac comment](https://core.trac.wordpress.org/ticket/45615#comment:39) mentioning the `upload_mimes` filter as a potential fix.

I recommend we also follow the example in this test where the filter is added and then immediately removed after Give is done with it so that it does not enable JSON uploads universally throughout the site, but instead only where needed for importing settings.

```php
/**
* @ticket 45615
* @dataProvider _wp_check_filetype_and_ext_unsupported
*/
function test_wp_check_filetype_and_ext_unsupported_filtered( $file, $filename, $expected ) {
     
    // With a filter these should succeed
    $ext = $expected['ext'];
    $mime_type = $expected['type'];
    $filter = function( $mimes ) use ( $ext, $mime_type ) {
        $mimes[ $ext ] = $mime_type;
        return $mimes;
    };
     
    add_filter( 'upload_mimes', $filter );
     
    $this->assertEquals( $expected, wp_check_filetype_and_ext( $file, $filename ) );
     
    remove_filter( 'upload_mimes', $filter );
}
```

**Comment by mathetos** [comment] 2019-01-19 16:01
I get nervous about removing the filter in the same function. If their JSON file is large will it timeout or the filter get removed before it's uploaded properly.

I think it's safer to just enable the filter on the Give admin screens.

**Closed** 2019-01-29 06:44 UTC
