### ISSUE TITLE
fix: ensure escaped characters don't display in emails

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#3775] opened 2018-10-17 03:26 UTC
# Bug Report

## User Story

As a donor I don't want to see backslashes (escape characters) in my emails. 

As an admin I don't want to confuse my donors with strange characters in their emails.

## Current Behavior

Escaped characters are displaying. See donor note:

![2018-10-16_20-21-44](https://user-images.githubusercontent.com/1571635/47060200-8361a100-d181-11e8-9f7a-71da291a5165.png)

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Add a donor note with a character like `'`
2. Preview email in MailHog or similar

## Related

#3774 

## Acceptance Criteria

- [ ] I can send _any_ email with an apostrophe and `\` don't appear.

**Comment by ravinderk** [comment] 2018-10-17 11:16
This issue will be automatically fix after: https://github.com/impress-org/give/issues/3774

**Comment by ravinderk** [comment] 2018-10-23 06:34
@kevinwhoffman I am closing this issue because I am unable to reproduce this in `release/2.3.0`

**Closed by ravinderk** 2018-10-23 06:34 UTC
