### ISSUE TITLE
fix: prevent stalled db upgrade by auto detecting background job status

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#4082] opened 2019-04-19 16:19 UTC
# Feature Request

## User Story
As an admin, I want completing DB upgraded with any issue.

DB upgrade in core process either in the background if possible otherwise on the page (by continuous ajax requests ) but we found that on few hosting servers that ajax works but it stops background job somehow. which means you will see stalled DB process and neither on page upgrade logic will work because ajax is working.

## Possible Solution
We can update on page upgrade trigger logic. Instead of checking if ajax works for on page update trigger or not we can track background process progress for certain time if we did not see any process then JS will auto trigger on page update with notice.

## Acceptance Criteria
- [ ] On page update trigger when background updater did not show any process in a specific interval.

**Comment by ravinderk** [comment] 2019-04-22 10:59
@DevinWalker @mathetos I left not here https://secure.helpscout.net/conversation/813412789/36700/#thread-2325918313

But for the record, it is difficult to fix locally because even after a few lines of code tweaks I cannot replicate the exact issue. I think it is better to reach the host server to the figureout issue because this happens only when we get false positive from `give_test_ajax_works`.

**Comment by mikejhale** [comment] 2019-08-01 21:45
Closing because we cannot reproduce the issue on the hosts we have access to.

**Closed by mikejhale** 2019-08-01 21:45 UTC
