### ISSUE TITLE
fix: prevent give_payment_note from affecting comment count

### ISSUE THREAD

**Issue by kevcampb** [impress-org/give#3588] opened 2018-08-09 04:57 UTC
The give plugin writes in to wp_comments with a comment_type of 'give_payment_note'

These database entires cause problems on the Wordpress Comments section on the admin site, as they appear in the total comment counts, but not show up due to the non-standard comment-type.

I cannot find any documentation on the purpose of these entries, so I'm unclear as to whether they can be deleted safely.

**Comment by ravinderk** [comment] 2018-08-09 06:08
@kevcampb 
I am unable to reproduce this issue. Please check video for more details:

https://www.useloom.com/share/a3171a16174749a4ad73ed98fde140b4

**Comment by ravinderk** [comment] 2018-08-09 08:56
@kevcampb As I told you this is my dev environment and I also installed woocommerce on this. Those `2380` comments out `2381` comments is from Woocommerce.

![image](https://user-images.githubusercontent.com/1784821/43888755-136a3550-9be0-11e8-87dc-d3f069227870.png)

**Comment by DevinWalker** [comment] 2018-09-14 17:49
Resolved via https://github.com/WordImpress/Give/issues/3627

**Comment by mehul0810** [comment] 2018-10-22 04:52
@kevinwhoffman While testing this issue and discussion with @ravinderk, it seems that we don't have a filter to exclude the comments count of `give_payment_note` in `wp_comment` due to which we have created a separate comments table for Give. Now, after migration as we are not deleting the comments data from `wp_comments` and its metatable. Then, this issue will still exist for customers as the Give comments exist in `wp_comments`. I would suggest having a health check plugin to delete comments from `wp_comments` and `wp_commentmeta` so that support team can help customers delete the Give comments from the old tables after confirming successful migration. Hence, re-opening the issue

Let me know your thoughts.

**Comment by mehul0810** [comment] 2018-10-22 04:52
@kevinwhoffman While testing this issue and discussion with @ravinderk, it seems that we don't have a filter to exclude the comments count of `give_payment_note` in `wp_comment` due to which we have created a separate comments table for Give. Now, after migration as we are not deleting the comments data from `wp_comments` and its metatable. Then, this issue will still exist for customers as the Give comments exist in `wp_comments`. I would suggest having a health check plugin to delete comments from `wp_comments` and `wp_commentmeta` so that support team can help customers delete the Give comments from the old tables after confirming successful migration. Hence, re-opening the issue

Let me know your thoughts.

**Comment by mehul0810** [comment] 2018-10-22 04:54
@kevinwhoffman While testing this issue and discussion with @ravinderk, it seems that we don't have a filter to exclude the comments count of `give_payment_note` in `wp_comment` due to which we have created a separate comments table for Give. Now, after migration as we are not deleting the comments data from `wp_comments` and its metatable. Then, this issue will still exist for customers as the Give comments exist in `wp_comments`. I would suggest having a health check plugin to delete comments from `wp_comments` and `wp_commentmeta` so that support team can help customers delete the Give comments from the old tables after confirming successful migration. Hence, re-opening the issue

Let me know your thoughts.

**Comment by mehul0810** [comment] 2018-10-22 04:57
@kevinwhoffman While testing this issue and discussion with @ravinderk, it seems that we don't have a filter to exclude the comments count of `give_payment_note` in `wp_comment` due to which we have created a separate comments table for Give. Now, after migration as we are not deleting the comments data from `wp_comments` and its metatable. Then, this issue will still exist for customers as the Give comments exist in `wp_comments`. I would suggest having a health check plugin to delete comments from `wp_comments` and `wp_commentmeta` so that support team can help customers delete the Give comments from the old tables after confirming successful migration. Hence, re-opening the issue

Let me know your thoughts.

**Comment by kevinwhoffman** [comment] 2018-10-23 03:07
## Slack Chat Summary

Participants: @DevinWalker @kevinwhoffman @ravinderk 
Topic: Whether to remove old comments in `2.3.0` or later
Result: We agree to take care of removing those old comments in `2.3.0` rather than wait for a future release, which would require another DB upgrade and cause support issues in the meantime.

@ravinderk Please move forward with the fix to remove old comments only if we can be sure that the comments have been successfully migrated to the custom tables.

**Comment by ravinderk** [comment] 2018-10-23 16:44
Closing this issue in favor of https://github.com/impress-org/give/issues/3737#issuecomment-432098048

**Closed by ravinderk** 2018-10-23 16:44 UTC
Labels: high-priority
