### ISSUE TITLE
fix: UI of currency switcher dropdown is broken with Give 2.4.1

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3992] opened 2019-02-07 13:42 UTC
# Bug Report

## User Story
As a user, I want to accept donations in any currency without issues with the currency switching dropdown so that I can donate in my preferred currency.

## Current Behavior
![image](https://user-images.githubusercontent.com/1852711/52415024-f2d21680-2b0b-11e9-8540-393b4c4cb231.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/1852711/52414870-763f3800-2b0b-11e9-9825-fa798b397e2c.png)

## Bug Type
- [x] This bug describes functionality that once worked as expected in Give version 2.4.0.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install Give `master` branch and Give - Currency Switcher `master` branch
2. Open Form Grid page and open the donation form in the popup
3. Now, Change Give to `release/2.4.1` branch and keep currency switcher to the `master` branch.
4. Again, follow step (2) and notice the difference.

## Acceptance Criteria
- [x] Currency Switcher dropdown should look and work properly

**Comment by DevinWalker** [comment] 2019-02-07 20:44
I finally found the cause of the issue and it is this commit: https://github.com/impress-org/give/commit/f4439276eacb59ffe9d7cbdee53044d2adc2a33b#diff-90d2d888332d5e47295ae690eff29eca 

I'm seeing if I can figure a workaround.

**Comment by DevinWalker** [comment] 2019-02-07 21:07
I've resolved this using the X-Theme specific method described here: https://github.com/impress-org/give/issues/3905#issuecomment-454492499

Here's the resolving commit: 607b1b185ffbaed6efe4eb8a109f47ee52542812

I've tested with X theme and default themes for compatibility.

**Closed by DevinWalker** 2019-02-07 21:07 UTC
