### ISSUE TITLE
feat: add advanced filters for Donors screen

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#1882] opened 2017-07-18 05:23 UTC
## User Story

As a Give admin, I want more control over my list of donors so that I can learn more about

## Possible Solution

Currently the filters for the donations aren't very feature rich. I propose we add more filters to the donations listing screen:

1. Search by Donor Name
2. Filter by Date (currently enabled)
3. Filter by Donation Form (currently possible through search but not very intuitive)

## Visuals

The location of the proposed filters:

![2018-01-31_17-46-31](https://user-images.githubusercontent.com/1571635/35656936-b45cca62-06ae-11e8-8337-4079f6f926dc.png)

Mockup of the Donor filters based on the same control bar that is present on the Donations screen:

![image](https://user-images.githubusercontent.com/1938671/47415853-6eb57800-d742-11e8-96ea-504dde8625da.png)

## Related
https://github.com/WordImpress/Give/issues/1199

## Acceptance Criteria

- [x] The old donor search bar has been removed.
- [x] When a string is entered into search, only donors whose names contain that string are displayed.
- [x] When start and end dates are provided, only donors created between those dates are displayed.
- [x] When only a start date is provided, it shows all donors created after that date.
- [x] When only an end date is provided, it shows all donors created before that date.
- [x] When a form is selected, only donors who have donated to that form are displayed.
- [x] When more than one control is manipulated, the filters have a stacking effect. e.g. You can search for donors with the last name "Smith" created between January and February who donated to a specific form. 
- [x] The Donation date filters work with a non-default date format in WP settings.
- [x] The Donor date filters work with a non-default date format in WP settings.
- [x] The search placeholder reads: `Name, Email, or Donation ID` (adjust input width if necessary so text is not cut off)
- [x] Searching for a Donation ID yields results for donations created with and without sequential ordering enabled.
- [x] The search controls work with filters such as `Completed` and `Subscriptions` that appear above the list table.
- [x] Each field label is aligned vertically with its respective input.

**Comment by kevinwhoffman** [comment] 2018-10-24 08:18
@nishitlangaliya We should be able to make use of the same control bar UI from the Donations screen for the Donors screen. See the visuals provided above.

I have also updated the acceptance criteria to describe the intended behavior based on the control bar.

**Comment by kevinwhoffman** [comment] 2018-10-25 06:36
## Slack Call Summary

Participants: @nishitlangaliya @kevinwhoffman 
Topic: Review design and acceptance criteria for donor filters
Result: Nishit has a clear understanding of the acceptance criteria. We are borrowing the design of the existing filters from the Donations screen. We have also clarified acceptance criteria regarding what should happen if only one start or end date is provided.

**Comment by nishitlangaliya** [comment] 2018-10-29 04:36
## Slack Call Summary

Participants: @nishitlangaliya @ravinderk 
Topic: Discussion regarding search input box search criteria.
Result: Currently, Search input was working base on tag like Name: or Note: so I had a confusion on that how we need to keep. So in that as per suggesion we will keep tag specific search also 
by default it will search on name. and also check if the search is email then check from email of Donor

**Comment by kevinwhoffman** [comment] 2018-10-29 06:02
## Slack Call Summary

Participants: @nishitlangaliya @kevinwhoffman 
Topic: Behavior of dat filters when a non-default date format is selected
Result: Nishit demonstrated how the date filters have no effect if a non-default date format is selected in WP settings. He will move forward with fixing these date filters in both Donations and Donors screens. Acceptance criteria updated.

**Comment by kevinwhoffman** [comment] 2018-10-31 05:30
@nishitlangaliya See updated acceptance criteria regarding notes from today's team call.

**Comment by nishitlangaliya** [comment] 2018-11-02 11:09
## Slack Call Summary

Participants: @nishitlangaliya @ravinderk  
Topic: Search by Donor ID was not working 
Result: I had a discussion with @ravinderk and found search by Donor ID was not working and after selecting correct base branch I got conflict so solving it and push the code.

**Comment by ravinderk** [comment] 2018-11-12 09:04
Reopening this issue for  https://github.com/impress-org/give/pull/3808#issuecomment-437779031

**Comment by ravinderk** [comment] 2018-11-12 10:06
Closing this issue as confirm by @nishitlangaliya : https://givewp.slack.com/archives/C0FAGC83C/p1542015472006600

**Closed by ravinderk** 2018-11-12 10:06 UTC
Labels: high-priority
